---
title: "PSY 710 - Big Data Analytics"
subtitle: Predicting Pirates of the Caribbean Wait Times
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path='Figs/', echo=FALSE, warning=FALSE, message=FALSE)
```

```{r, feat_libs, include=FALSE}
shhh = function(...) {
    suppressWarnings(
        suppressPackageStartupMessages(base::library(...))
    )}

#load libraries
shhh(tidyverse)
shhh(lubridate)
```

```{r, feature_engineering, include=FALSE}
#read in pirates of carribean data
pir_raw = read_csv('../../data/disneydata/pirates_of_caribbean.csv', 
                   col_names = T)

#read in metaata
meta_raw = read_csv('../../data/disneydata/metadata.csv', col_names = TRUE, 
                    #change guess arg to better guage col type
                    guess_max = 5000)

#wrangle pirate of carribean dataset
pir = pir_raw %>% 
    replace_na(list('SPOSTMIN' = 0, 'SACTMIN' = 0)) %>% #replace NAs with 0s
    mutate(
        'date' = mdy(date), #change date format
        #NY timezone - default apparently is UTC 
        datetime = force_tz(as.POSIXct(datetime), tzone = "America/New_York"),
        #only one time is available per obs so combine features
        'waittime' = SPOSTMIN + SACTMIN,
        #rm rows with NULL
        'SPOSTMIN' = NULL, 
        'SACTMIN' = NULL) %>% 
    filter(waittime != -999 & waittime != -7) #ride closed indicators

#wrangle metadata before merging
meta = meta_raw %>% 
    rename_all(list(tolower)) %>% #changes column names to lowercase
    select(
        date, 
        "day" = dayofweek,
        "week" = weekofyear, 
        'month' = monthofyear, 
        season, 
        'holiday_prox' = holidaypx,
        'holiday_rnk' = holidaym, 
        'holiday_name' = holidayn, 
        'holiday_YorN' = holiday, 
        'wdw_event_code' = wdwevent, 
        'wdw_race' = wdwrace, 
        'temp_mean' = wdwmeantemp, 
        'temp_max' = wdwmaxtemp, 
        'temp_min' = wdwmintemp, 
        'mk_event' = mkeventn, 
        'ep_event' = epeventn, 
        'hs_event' = hseventn, 
        'ak_event' = akeventn,
        'insesh_all' = insession, 
        'insesh_sqrt' = insession_sqrt_wdw,
        'insesh_cntrl_fl' = insession_central_fl, 
        'insesh_fl' = insession_florida,
        'mk_extra_morn' = mkemhmorn, 
        'mk_extra_eve' = mkemheve, 
        'mk_total_hrs' = mkhoursemh,
        'ep_extra_morn' = epemhmorn, 
        'ep_extra_eve' = epemheve, 
        'ep_total_hrs' = ephoursemh,
        'hs_extra_morn' = hsemhmorn, 
        'hs_extra_eve' = hsemheve, 
        'hs_total_hrs' = hshoursemh,
        'ak_extra_morn' = akemhmorn, 
        'ak_extra_eve' = akemheve, 
        'ak_total_hrs' = akhoursemh,
        'event' = partyseason_wdw, 
        'hist_precip' = weather_wdwprecip, 
        'mk_cap_lost' = capacitylost_mk, 
        'ep_cap_lost' = capacitylost_ep, 
        'hs_cap_lost' = capacitylost_hs, 
        'ak_cap_lost' = capacitylost_ak, 
        'mk_day_parades' = mkprdday, 
        'mk_fireworks' = mkfirewk,
        'ep_fireworks' = epfirewk, 
        'hs_day_parades' = hsprdday, 
        'hs_fireworks' = hsfirewk, 
        'hs_nightshows' = hsshwngt, 
        'ak_day_parades' = akprdday, 
        'ak_nightshows' = akshwngt
        ) %>% 
    mutate(
        date = mdy(date), #changes date format to match pir_raw
        #change fct levels 
        day = recode(factor(day), 
                     `1` = 'Sun', `2` = 'Mon', `3` = 'Tues', `4` = 'Wed', 
                     `5` = 'Thurs', `6` = 'Fri', `7` = 'Sat'), 
        month = recode(factor(month), 
                       `1` = 'Jan', `2` = 'Feb', `3` = 'Mar', `4` = 'Apr', 
                       `5` = 'May', `6` = 'Jun', `7` = 'July', `8` = 'Aug', 
                       `9` = 'Sept', `10` = 'Oct', `11` = 'Nov', `12` = 'Dec'),
        #change season to title case; shorten MLK Jr day
        season = recode(factor(str_to_title(season)),
                        "Martin Luther King Junior Day" = "MLK Jr. Day"),
        holiday_name = str_to_upper(holiday_name), 
        holiday_YorN = recode(factor(holiday_YorN),
                              `0` = 'No', `1` = 'Yes'), 
        wdw_event_code = recode(factor(wdw_event_code), 
                                `0` = "No Event", `1` = "Some Event"), 
        wdw_race = recode(factor(wdw_race),
                          `0` = "No Race", `1` = "Some Race"),
        # *mk_event, ep_event, ak_event all need to drop_&_replace NA for factor, 
        event = factor(str_to_upper(event)) #change codes to upper case
    ) %>% 
    mutate_if(is.numeric, list(as.double))

# #to handle multiple mutate_at calls
mutate2 <- function(data, .vars, .funs) {
    stopifnot(length(.vars) == length(.funs))

    for (i in seq_along(.vars)) {
        data <- mutate_at(data, .vars[[i]], .funs[[i]])
    }
    data
}

meta = meta %>% 
    mutate2(
        list(vars(starts_with("insesh_")), vars(ends_with("_event")), 
             vars(ends_with("_name"))), 
        list(~ parse_number(.) / 100, ~ replace_na(., "NONE"), 
             ~replace_na(., "No Holiday"))
    ) %>% 
    mutate_if(is.character, as.factor)


#merge datasets by date
mrg_dat = merge(pir, meta, by = 'date') %>% 
    mutate(
        datetime = strftime(datetime, format = '%H:%M'), #extract time only
        #create new fct feature with appropriate levels
        timeofday = as.factor(case_when(
            datetime >= "05:00" & datetime <= "11:59" ~ "Morning",
            datetime >= "12:00" & datetime <= "15:59" ~ "Afternoon",
            datetime >= "16:00" & datetime <= "19:59" ~ "Evening",
            datetime >= "20:00" & datetime <= "23:59" ~ "Night",
            datetime >= "00:00" & datetime <= "04:59" ~ "Extended Hrs"
        ))
    ) %>% 
    mutate_at(
        vars(contains("extra_")), as.factor 
        ) #changes specific features to fct

#final wrangled dataset
dat = mrg_dat %>% 
    select(-datetime) %>%  #rm date and datetime features
    drop_na()
```

```{r, include=FALSE}
#df structure
cat("The dataframe has", dim(dat)[1], "rows and", dim(dat)[2], "features")
glimpse(dat)
```

```{r echo=TRUE}
#summary statistics of df
select_if(dat, is.numeric) %>%
    sapply(function(x) summary(x)) %>% 
    round(2)
```

## Outlier Analysis

```{r}
#create a df to handle updated values
dat_cap = dat
```

```{r, include=FALSE}
#outlier detection
cappedOutliers <- function(dt, var, gtitle = NULL) {
    gtitle = as.character(gtitle)
    var_name <- eval(substitute(var), eval(dt))
    
    tot <- sum(!is.na(var_name))
    na1 <- sum(is.na(var_name))
    
    m1 <- mean(var_name, na.rm = T)
    
    par(mfrow = c(2, 2), oma = c(0, 0, 3, 0))
    
    boxplot(var_name, main = "With Outliers")
    hist(var_name, main = "With Outliers", xlab = NA, ylab = NA)
    
    outlier <- boxplot.stats(var_name)$out
    mo <- mean(outlier)
    
    cap_func = function(x) {
        quants = quantile(x, probs = c(.25, .75), na.rm = TRUE)
        caps = quantile(x, probs = c(.05, .95), na.rm = TRUE)
        H = 1.5 * IQR(x, na.rm = TRUE)
        
        x[x < (quants[1] - H)] <- caps[1]
        x[x > (quants[2] + H)] <- caps[2]
        
        return(x)
    }
    
    var_name <- ifelse(var_name %in% outlier, cap_func(var_name), var_name)
    
    boxplot(var_name, main = "With Capped Outliers")
    hist(var_name, main = "With Capped Outliers", xlab = NA, ylab = NA)
    
    title(paste("Outlier Check: ", gtitle), outer = TRUE)
    
    na2 <- sum(is.na(var_name))
    
    #message("Outliers Identified: ", na2 - na1, " from ", tot, " Observations")
    #message("Proportion (%) of Outliers: ", round((na2 - na1) / tot * 100), 2, "%")
    message("Mean of the Outliers: ", round(mo, 2))
    
    m2 <- mean(var_name, na.rm = T)
    
    message("Mean without Capping Outliers: ", round(m1, 2))
    message("Mean if Outliers are Capped: ", round(m2, 2))
    
    dt[as.character(substitute(var))] <- invisible(var_name)
    assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
    message("Outliers successfully capped", "\n")
        
    return(invisible(dt))
}
```

```{r echo=FALSE}
cappedOutliers(dat_cap, waittime, "Waittime")
cappedOutliers(dat_cap, holiday_prox, "Holiday Proximity")
cappedOutliers(dat_cap, temp_mean, "Mean Temperature")
cappedOutliers(dat_cap,temp_max , "Max Temperature")
cappedOutliers(dat_cap, temp_min, "Min Temperature")
cappedOutliers(dat_cap, mk_total_hrs, "MK Total Hrs")
cappedOutliers(dat_cap, ep_total_hrs, "EP Total Hrs")
cappedOutliers(dat_cap, hs_total_hrs, "HS Total Hrs")
cappedOutliers(dat_cap, ak_total_hrs, "AK Total Hrs")
cappedOutliers(dat_cap, mk_cap_lost, "MK Capacity Lost")
cappedOutliers(dat_cap, ep_cap_lost, "EP Capacity Lost")
cappedOutliers(dat_cap, hs_cap_lost, "HS Capacity Lost")
cappedOutliers(dat_cap, ak_cap_lost, "AK Capacity Lost")
```

```{r}
#summary statistics of capped df
select_if(dat_cap, is.numeric) %>%
    sapply(function(x) summary(x)) %>% 
    round(2)
```

```{r, include=FALSE}
shhh(GGally)
library(corrplot)
shhh(RColorBrewer)

corrs <- cor(select_if(dat_cap, is.numeric), use="pairwise.complete.obs")
```

```{r, echo=FALSE}
dev.off()
#disregarded features: fireworks
corrplot(corrs, type = "lower", diag = FALSE, method = "circle", tl.pos = "ld", 
         tl.srt = 45, tl.col = "black", tl.offset = .5, tl.cex = .75
       # label = TRUE, label_size = 3,
       # low = "#F21A00", high = "#3B9AB2",
       # hjust = .65,
       # size = 3,
       # layout.exp = 2,
       # angle = 300
       )
```

```{r, include=FALSE}
#### EDA Viz ####
library(cowplot) #masks libridate::stamp
library(gridExtra) #masks 'dplyr::combine

#create dfs with categorical & continuous variables
sep_vars = list(
    cat_vars = dat_cap[which(sapply(dat_cap, is.factor))],
    cont_vars = dat_cap[which(sapply(dat_cap, is.numeric))]
    )

#create a list with freq table for each feature
freqList = lapply(sep_vars[["cat_vars"]],
                  function(x) {

                      my_lst = data.frame(table(x))
                      names(my_lst) = c("fct", "n")

                      return(my_lst)
                        }
                    )
freqList
```

```{r, include=FALSE}
#function to automate lolipop plots
loliPlots <- function(data_in, i, ...) {
    args = list(...)
    
    data <- data_in[[i]]  
    
    p <- ggplot(data = data, aes(x = fct, y = n, label = n)) + 
            geom_point(size = 3, color = "red", alpha = .6, shape = 20, 
                       stroke = 2) + 
            geom_segment(aes(x = fct, xend = fct, y = 0, yend = n), 
                         color = "black") + 
            coord_flip() + 
            theme_minimal() + 
            labs(title = " ", 
                 x = str_to_title(i), 
                 y = "Total Count") +
        #geom_text(nudge_x = .45) +
            theme(panel.grid.major.y = element_blank(), 
                  panel.border = element_blank(), 
                  axis.ticks.y = element_blank(), 
                  legend.position = 'none')
    
    return(p)
}
```

```{r, include=FALSE}
#list of lolipop plots
loliList = list(
    p_day = loliPlots(data_in = freqList, i = "day"),
    p_month = loliPlots(data_in = freqList, i = "month"),
    p_season = loliPlots(data_in = freqList, i = "season"),
    p_mkevent = loliPlots(data_in = freqList, i = "mk_event"),
    p_epevent = loliPlots(data_in = freqList, i = "ep_event"),
    p_hsevent = loliPlots(data_in = freqList, i = "hs_event"),
    p_akevent = loliPlots(data_in = freqList, i = "ak_event"),
    p_time = loliPlots(data_in = freqList, i = "timeofday"),
    p_event = loliPlots(data_in = freqList, i = "event")
    )
```

```{r}
# title of graphs
title = ggdraw() + 
    draw_label(
        "Frequency Tables of Categorical Features",
        fontface = "bold"
        )
        
#categorical plots with titles! - save both separately
plot_grid(title, plotlist = loliList[c(1, 4, 3)], ncol = 2, 
          rel_heights = c(.1, .1))
plot_grid(title, plotlist = loliList[c(2, 5, 6)], ncol = 2, 
          rel_heights = c(.1, .1))
plot_grid(title, plotlist = loliList[c(7, 9, 8)], ncol = 2, 
          rel_heights = c(.1, .1))
```

```{r}
#density plots for continuous features
library(e1071)

plotDen <- function(data_in, i) {
    data <- data.frame(x = data_in[[i]], waittime = data_in$waittime)
    
    p <- ggplot(data = data) + 
            geom_line(aes(x = x), stat = 'density', size = 1, alpha = 1.0) + 
        xlab(paste0(
            (colnames(data_in)[i]), '\n', 'Skewness: ', 
                    round(skewness(data_in[[i]], na.rm = TRUE), 2))
            ) + 
        theme_minimal() 
    
    return(p)
}

#arrange graphs for continuous features
doPlots <- function(data_in, fun, ii, ncol = 3) {
    pp <- list()
    
    for (i in ii) {
        p <- fun(data_in = data_in, i = i)
        pp <- c(pp, list(p))
    }
    
    do.call("grid.arrange", c(pp, ncol = ncol))
}

#density plots!
doPlots(sep_vars[["cont_vars"]], fun = plotDen, ii = 2:8, ncol = 3)
doPlots(sep_vars[["cont_vars"]], fun = plotDen, ii = 9:15, ncol = 3)
doPlots(sep_vars[["cont_vars"]], fun = plotDen, ii = 16:22, ncol = 3)
doPlots(sep_vars[["cont_vars"]], fun = plotDen, ii = 23:28, ncol = 3)
```

```{r, echo = FALSE}
##plot the waittimes for each time of day by c(month, season) possible facets?
ggplot(dat_cap, aes(x = month, y = waittime, fill = month)) + 
    geom_bar(position = "stack", stat = "identity") +
    facet_wrap(~timeofday) + 
    labs(
        title = "Monthly Count by Time of Day", 
        caption = "Good to be a night owl!"
    )

#histogram of response variable!
ggplot(dat_cap, aes(x = waittime)) + 
    geom_histogram(col = 'black', fill = "darkgray", binwidth = 4.5) + 
    theme_minimal() + 
    scale_x_continuous() + 
    labs(
        title = "Histogram of Response Variable", 
        subtitle = "Wait Times", 
        caption = "Outliers are capped!"
    )
```

```{r, echo=FALSE}
#transforom data using norm function
normalize = function(x) {
    return(
        (x - min(x)) / (max(x) - min(x))
    )
}

#normalize all numeric features
dat_norm = dat_cap %>%
    mutate_if(is.numeric, normalize)
    # add_column("date" = dat[, 1], .before = 1)

#write out the final normalized df if wanted
#write_csv(dat_norm, path = "../../data/finalnorm_df.csv")
```










